{
 "title": "lab10",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Number of Crimes",
   "type": "xychart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT COUNT(crime_id) AS \"crimes_num\", crime_year FROM crimes_copy GROUP BY crime_year ORDER BY crime_year LIMIT 1000 "
    }
   ]
  },
  {
   "title": "Crime Types",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT crime_type, crime_id FROM crimes_copy "
    }
   ]
  },
  {
   "title": "Home Towns of Suspects",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT home_town, suspect_id FROM suspects ORDER BY home_town"
    }
   ]
  },
  {
   "title": "Ages of Suspects",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT suspect_id, age FROM suspects ORDER BY age LIMIT 1000 "
    }
   ]
  },
  {
   "title": "Genders of Suspects",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT gender, suspect_id FROM suspects"
    }
   ]
  }
 ]
}